#!/usr/bin/env python3
"""Render txgemma_scaffold_proposals.json as a self-contained HTML report."""

import argparse
import json
import os
import html
from pathlib import Path
from typing import Optional


CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, sans-serif; background: #f8f9fa; color: #212529; }
header { background: #1a1a2e; color: #fff; padding: 2rem; }
header h1 { font-size: 1.6rem; font-weight: 600; }
header p { margin-top: 0.4rem; font-size: 0.9rem; color: #adb5bd; }
.toc { background: #fff; border-bottom: 1px solid #dee2e6; padding: 1rem 2rem; }
.toc h2 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em;
          color: #6c757d; margin-bottom: 0.5rem; }
.toc ul { display: flex; flex-wrap: wrap; gap: 0.5rem; list-style: none; }
.toc a { text-decoration: none; color: #0d6efd; font-size: 0.85rem;
         padding: 0.2rem 0.6rem; border: 1px solid #0d6efd; border-radius: 4px; }
.toc a:hover { background: #0d6efd; color: #fff; }
main { max-width: 960px; margin: 2rem auto; padding: 0 1.5rem; }
.card { background: #fff; border: 1px solid #dee2e6; border-radius: 8px;
        margin-bottom: 2rem; overflow: hidden; }
.card-header { background: #1a1a2e; color: #fff; padding: 1rem 1.5rem;
               display: flex; align-items: baseline; gap: 1rem; }
.card-header h2 { font-size: 1.15rem; }
.card-header .meta { font-size: 0.8rem; color: #adb5bd; }
.card-body { padding: 1.5rem; }
.regions { background: #f1f3f5; border-radius: 4px; padding: 0.6rem 1rem;
           font-size: 0.85rem; margin-bottom: 1.2rem; }
.regions strong { color: #495057; }
.section-label { font-size: 0.75rem; font-weight: 700; text-transform: uppercase;
                 letter-spacing: 0.06em; color: #6c757d; margin: 1.2rem 0 0.4rem; }
.section-label:first-child { margin-top: 0; }
.response { white-space: pre-wrap; font-size: 0.88rem; line-height: 1.65;
            background: #f8f9fa; border-left: 3px solid #0d6efd;
            padding: 0.8rem 1rem; border-radius: 0 4px 4px 0; }
.response.scaffold { border-color: #20c997; }
footer { text-align: center; font-size: 0.8rem; color: #adb5bd; padding: 2rem; }
"""


def escape(text: str) -> str:
    return html.escape(text or "")


def card(entry: dict) -> str:
    gene = escape(entry.get("gene_symbol", ""))
    acc = escape(entry.get("uniprot_accession", ""))
    regions = escape(entry.get("brain_regions", ""))
    z_scores = escape(entry.get("z_scores", ""))
    seq_len = entry.get("sequence_length", "")
    analysis = escape(entry.get("structural_analysis", ""))
    scaffolds = escape(entry.get("scaffold_proposals", ""))

    return f"""
<div class="card" id="{gene}">
  <div class="card-header">
    <h2>{gene}</h2>
    <span class="meta">{acc} &bull; {seq_len} aa</span>
  </div>
  <div class="card-body">
    <div class="regions">
      <strong>Top enriched brain regions:</strong> {regions}<br>
      <strong>Z-scores:</strong> {z_scores}
    </div>
    <div class="section-label">Structural analysis</div>
    <pre class="response">{analysis}</pre>
    <div class="section-label">Scaffold proposals</div>
    <pre class="response scaffold">{scaffolds}</pre>
  </div>
</div>"""


def render(input_json: str, out_html: str) -> None:
    with open(input_json) as f:
        entries = json.load(f)

    toc_items = "".join(
        f'<li><a href="#{html.escape(e.get("gene_symbol",""))}">'
        f'{html.escape(e.get("gene_symbol",""))}</a></li>'
        for e in entries
    )
    cards = "".join(card(e) for e in entries)

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Orphan GPCR Scaffold Proposals — TxGemma</title>
<style>{CSS}</style>
</head>
<body>
<header>
  <h1>Orphan GPCR Scaffold Proposals</h1>
  <p>Generated by TxGemma-Chat &bull; {len(entries)} receptors</p>
</header>
<nav class="toc">
  <h2>Receptors</h2>
  <ul>{toc_items}</ul>
</nav>
<main>{cards}</main>
<footer>Generated from {os.path.basename(input_json)}</footer>
</body>
</html>"""

    Path(out_html).parent.mkdir(parents=True, exist_ok=True)
    with open(out_html, "w") as f:
        f.write(page)
    print(f"Wrote {len(entries)} receptor cards → {out_html}")


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render TxGemma scaffold proposals JSON as HTML."
    )
    parser.add_argument(
        "--input_json",
        default=os.path.join("data", "txgemma_scaffold_proposals.json"),
    )
    parser.add_argument(
        "--out",
        default=os.path.join("data", "txgemma_scaffold_report.html"),
    )
    args = parser.parse_args(argv)
    render(args.input_json, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
